### PR TITLE
Move data files from data-viz-of-the-week

### PR DESCRIPTION
**Pull request by jswan5**
Move large files over to new repository (for baseball and climate-change DVotW); will update code in notebooks to point to new location, and remove files in existing data-viz-of-the-week repository.

Refer to CC-2001

### CODE REVIEW

**Review by byrcyb — COMMENTED** [review]
@jswan5 changes look good. My only question is whether we want to keep image files in the original repo or move them over to this one. I'm not sure where to draw the line I guess. These images are pretty small in size so I'd be inclined to leave it in the other repo and not include it here. Thoughts?

**Comment by jswan5** [comment]
That's a good point, it's important to be consistent with the policy. I've also picked up CC-1987 so it can be formalized.

My thoughts were that there's some logic to having all the supporting files in the same repository, especially if some of the images are larger. But maybe it makes more sense to have a rule based purely on file size? Is there the possibility of running into limits with the `data-files` repository as well?

**Comment by byrcyb** [comment]
I think repo size maximum is somewhere in the neighbourhood of less than 5GB, with a maximum file size of 100 MB. So we should be ok for the time being and could create additional data-files repos if needed. I know that if an image in a notebook is remotely located then when people try to download a pdf or html version of the notebook from the hub they will get a missing image icon in the file. So I think for that reason I'd vote to keep explanatory images local but other supporting files (visualization html and data files including images if the data are images) remote. We could also say that if any of your supporting files are > 1 MB then use the data-files repo.

**Review by byrcyb — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
